// Re-exported from @cepseudo/shared for backward compatibility
export type {
    DataResponse,
    MulterFile,
    TypedRequest,
    AuthenticatedTypedRequest,
    EndpointHandler,
    GenericHandler,
    IdParamRequest,
    NoParamRequest,
    AssetUploadBody,
    AssetUpdateBody,
    AssetUploadRequest,
    AssetGetRequest,
    AssetUpdateRequest,
    AssetDeleteRequest,
    BatchAssetData,
    BatchUploadBody,
    BatchUploadRequest,
    CustomTableListQuery,
    CustomTableListRequest,
    CustomTableGetRequest,
    CustomTableCreateRequest,
    CustomTableUpdateRequest,
    TilesetUploadRequest,
    TilesetListQuery,
    TilesetListRequest
} from '@cepseudo/shared'
